#how to deploy a xml action file for github https://myridia.com/dev_posts/view/3904
name: Publish
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

  
jobs:
  Tasks:
    runs-on: ubuntu-latest
    container: myridia/runner
    steps:
      - name: python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Install Poetry
        run: |
         # sudo apt-get update -y
         pipx install poetry 
         echo 'export PATH="$PATH:/$HOME/.local/bin/"' >> ~/.bashrc
         pipx ensurepath 
         pipx completions
         
      - name: Checkout
        run:  |       
          git clone 'https://github.com/myridia/django-file-captcha.git'

      - name: Build
        run: |
          cd django-file-captcha          
          export PATH="$HOME/.local/bin:$PATH"
          pip install build hatchling
          python -m build 
          # poetry add setuptools wheel build
          # poetry run python -m build 
          # poetry remove setuptools wheel build
          # poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }} 

     
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'django-file-captcha/dist/*'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

        
